"use server";

import { z } from "zod";
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { getSessionUser } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { identifyImage } from "@/lib/utils/image-bytes";
import { fail, ok, type Result } from "@/types/domain";
import type { Insert } from "@/types/database";

const MAX_PROOF_BYTES = 8 * 1024 * 1024; // matches bucket file_size_limit
const MAX_SUBMISSIONS_PER_HOUR = 5;

const SubmitSchema = z.object({
  package_id: z.string().uuid("Pick a package."),
  pubg_id: z
    .string()
    .trim()
    .min(6, "PUBG ID looks too short.")
    .max(32, "PUBG ID looks too long.")
    .regex(/^[0-9]+$/, "PUBG ID is digits only."),
  ign: z.string().trim().min(1, "IGN required.").max(32),
  payment_method: z.enum(["baridimob", "ccp"]),
  transfer_code: z
    .string()
    .trim()
    .max(64)
    .optional()
    .transform((v) => (v && v.length > 0 ? v : null)),
  whatsapp_phone: z
    .string()
    .trim()
    .min(8, "WhatsApp number required.")
    .max(20),
  email: z
    .string()
    .trim()
    .email("Invalid email.")
    .optional()
    .or(z.literal(""))
    .transform((v) => (v && v.length > 0 ? v : null)),
});

export interface SubmitUcResult {
  request_number: string;
  locale: "en" | "ar";
}

export async function submitUcRechargeAction(
  formData: FormData,
): Promise<Result<SubmitUcResult>> {
  const session = await getSessionUser();
  if (!session) return fail("Sign in to submit a UC recharge request.");

  const parsed = SubmitSchema.safeParse({
    package_id: formData.get("package_id"),
    pubg_id: formData.get("pubg_id"),
    ign: formData.get("ign"),
    payment_method: formData.get("payment_method"),
    transfer_code: formData.get("transfer_code") ?? "",
    whatsapp_phone: formData.get("whatsapp_phone"),
    email: formData.get("email") ?? "",
  });
  if (!parsed.success) {
    return fail(parsed.error.issues[0]?.message ?? "Check your details.");
  }
  const data = parsed.data;

  // Locale only used to revalidate the right status page slug.
  const localeRaw = String(formData.get("locale") ?? "en");
  const locale: "en" | "ar" = localeRaw === "ar" ? "ar" : "en";

  // Proof file required.
  const proofFile = formData.get("proof");
  if (!(proofFile instanceof File) || proofFile.size === 0) {
    return fail("Upload a proof of payment.");
  }
  if (proofFile.size > MAX_PROOF_BYTES) {
    return fail("Proof file exceeds 8 MB.");
  }
  // Validate by actual file bytes — Content-Type from the browser is
  // attacker-controlled. Only PNG / JPEG / WebP are accepted.
  const proofBuffer = Buffer.from(await proofFile.arrayBuffer());
  const identified = identifyImage(proofBuffer);
  if (!identified) {
    return fail("Proof must be a PNG, JPEG, or WebP image.");
  }

  const admin = createAdminClient();

  // Rate limit: cap submissions per user per hour to slow spam / abuse.
  const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000).toISOString();
  const { count: recentCount } = await admin
    .from("uc_recharge_requests")
    .select("id", { count: "exact", head: true })
    .eq("user_id", session.id)
    .gte("created_at", oneHourAgo);
  if ((recentCount ?? 0) >= MAX_SUBMISSIONS_PER_HOUR) {
    return fail(
      `Too many requests in the last hour (limit ${MAX_SUBMISSIONS_PER_HOUR}). Try again later.`,
    );
  }

  // 1. Re-fetch the package as source of truth for price + UC + active flag.
  const { data: pkg, error: pkgErr } = await admin
    .from("uc_packages")
    .select("id, uc_amount, bonus_uc, price_dzd, is_active")
    .eq("id", data.package_id)
    .maybeSingle<{
      id: string;
      uc_amount: number;
      bonus_uc: number;
      price_dzd: number;
      is_active: boolean;
    }>();
  if (pkgErr || !pkg) return fail("Package not found.");
  if (!pkg.is_active) return fail("This package is no longer available.");

  // 2. Upload proof into the user's folder. The bucket policy enforces this
  // path shape for direct uploads, but here we use the service-role admin
  // client so the policy is bypassed — we still keep the same convention so
  // the file is owned by the user logically.
  const proofPath = `${session.id}/${randomUUID()}.${identified.ext}`;
  const { error: uploadErr } = await admin.storage
    .from("uc-proofs")
    .upload(proofPath, proofBuffer, {
      // contentType derived from the sniffed bytes, not the upload header,
      // so a spoofed Content-Type can't bypass bucket allowed_mime_types.
      contentType: identified.mime,
      cacheControl: "31536000, immutable",
      upsert: false,
    });
  if (uploadErr) return fail(`Upload failed: ${uploadErr.message}`);

  // 3. Insert the request. request_number is generated by the column default.
  const insert: Insert<"uc_recharge_requests"> = {
    user_id: session.id,
    package_id: pkg.id,
    uc_amount_snapshot: pkg.uc_amount,
    bonus_uc_snapshot: pkg.bonus_uc,
    price_dzd_snapshot: pkg.price_dzd,
    pubg_id: data.pubg_id,
    ign: data.ign,
    payment_method: data.payment_method,
    transfer_code: data.transfer_code,
    proof_url: proofPath,
    whatsapp_phone: data.whatsapp_phone,
    email: data.email,
  };

  const { data: inserted, error: insertErr } = await admin
    .from("uc_recharge_requests")
    .insert(insert as never)
    .select("request_number")
    .single<{ request_number: string }>();
  if (insertErr || !inserted) {
    // Best-effort rollback of the uploaded proof so we don't orphan files.
    await admin.storage.from("uc-proofs").remove([proofPath]);
    return fail(insertErr?.message ?? "Couldn't save request.");
  }

  revalidatePath("/admin/uc-recharges");
  return ok({ request_number: inserted.request_number, locale });
}

const LookupSchema = z.object({
  query: z.string().trim().min(3, "Enter your request number or transfer code."),
});

export interface LookupUcResult {
  request_number: string;
}

// Public lookup: returns the request_number to redirect to /uc-recharge/{n}.
// Uses admin client because the public anonymous user has no RLS access.
export async function lookupUcRequestAction(
  formData: FormData,
): Promise<Result<LookupUcResult>> {
  const parsed = LookupSchema.safeParse({ query: formData.get("query") });
  if (!parsed.success) return fail(parsed.error.issues[0]?.message ?? "Invalid query.");
  const term = parsed.data.query.replace(/[%_]/g, "");

  const admin = createAdminClient();
  // Try exact match on request_number first, then transfer_code.
  let row = null as { request_number: string } | null;
  {
    const { data } = await admin
      .from("uc_recharge_requests")
      .select("request_number")
      .eq("request_number", term.toUpperCase())
      .maybeSingle<{ request_number: string }>();
    row = data ?? null;
  }
  if (!row) {
    const { data } = await admin
      .from("uc_recharge_requests")
      .select("request_number")
      .eq("transfer_code", term)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle<{ request_number: string }>();
    row = data ?? null;
  }
  if (!row) return fail("No request matches that input.");
  return ok({ request_number: row.request_number });
}
